import Link from "next/link";
import styles from "../styles/LocationLanding.module.css";
import { locationPageEntries } from "../data/locationSeo";

export default function LocationCorporateGifts({ location, page }) {
  const peers = locationPageEntries.filter((entry) => entry.slug !== location);
  const url = `https://printkee.com/${location}/corporate-gifts`;
  const breadcrumbs = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://printkee.com" }, { "@type": "ListItem", position: 2, name: "Locations", item: "https://printkee.com/locations" }, { "@type": "ListItem", position: 3, name: `Corporate Gifts in ${page.name}`, item: url }] };
  const webPage = { "@context": "https://schema.org", "@type": "WebPage", name: page.title, description: page.description, url, about: { "@type": "Thing", name: "Corporate gifting" } };
  const faqs = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [["What should a corporate gifting brief include?", "Include recipient type, quantity, budget guidance, preferred product categories, branding requirements, delivery locations and required-in-hand date."], ["Can corporate gifts include company branding?", "Many Printkee product categories support custom branding. Confirm the available method, placement and artwork requirements for the specific item before approval."], ["How should a team plan a bulk corporate-gifting order?", "Start with recipient groups and a required-in-hand date, then confirm product suitability, branding details and delivery information for the selected items."]].map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPage) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqs) }} /><main className={styles.page}>
    <header className={styles.hero}><p>Corporate gifting solutions</p><h1>Corporate Gifts in {page.label}</h1><span>{page.intro}</span></header>
    <div className={styles.content}>
      <nav className={styles.breadcrumbs} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/locations">Locations</Link><span>/</span><span>Corporate Gifts in {page.name}</span></nav>
      <section><h2>Corporate gifting for {page.name} businesses</h2><p>{page.context}</p><p>Printkee’s <Link href="/collection">corporate gift collection</Link> supports {page.useCase}. Consider the recipient, campaign purpose, budget guidance and desired brand presence before narrowing the range.</p></section>
      <section className={styles.grid}><div><h2>Build a relevant shortlist</h2><p>Choose useful items rather than applying one format to every audience. <Link href="/technology-accessories">Technology accessories</Link> can suit desk-based teams; <Link href="/eco-products">eco-conscious gifting options</Link> can support a sustainability-led brief; and <Link href="/drink-ware">branded drinkware</Link> offers everyday utility.</p></div><div><h2>Branding and presentation</h2><p>Confirm logo placement, artwork, packaging requirements and the approval point for the chosen items. A restrained brand treatment and a clear message usually create a better recipient experience than adding branding to every surface.</p></div></section>
      <section><h2>A practical process for bulk corporate gifts</h2><ol><li>Define employee, client or event recipient groups.</li><li>Set quantity, budget guidance and the required-in-hand date.</li><li>Shortlist product categories and confirm customisation details.</li><li>Share delivery locations and nominate an internal approval owner.</li></ol></section>
      <section className={styles.cta}><h2>Discuss corporate gifts for {page.name}</h2><p>Send your audience, quantity, branding and delivery requirements so the team can help identify appropriate options.</p><Link href="/contact">Request a corporate gifting quote</Link></section>
      <section><h2>Frequently asked questions</h2><h3>What should a corporate gifting brief include?</h3><p>Include recipient type, quantity, budget guidance, preferred product categories, branding requirements, delivery locations and required-in-hand date.</p><h3>Can corporate gifts include company branding?</h3><p>Many Printkee product categories support custom branding. Confirm the available method, placement and artwork requirements for the specific item before approval.</p><h3>How should a team plan a bulk corporate-gifting order?</h3><p>Start with recipient groups and a required-in-hand date, then confirm product suitability, branding details and delivery information for the selected items.</p></section>
      <section className={styles.nearby}><h2>Corporate gifting in other NCR locations</h2>{peers.map((entry) => <Link key={entry.slug} href={`/${entry.slug}/corporate-gifts`}>Corporate gifts in {entry.name}</Link>)}</section>
    </div>
  </main></>;
}
